### ISSUE TITLE
Maybe mxnet bug in net init?

### ISSUE THREAD

**Issue by nopattern** [AmigoCDT/MXNet-EfficientNet#1]
I have test your EfficintNet code of version b0,b1 which is good. But failed at 'b2', The error info is as following:
  

> infer_shape error. Arguments:
  data: (1, 35, 208, 208)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/mxnet-1.3.1-py3.6.egg/mxnet/gluon/block.py", line 912, in forward
    params = {i: j.data(ctx) for i, j in self._reg_params.items()}
  File "/usr/local/lib/python3.6/dist-packages/mxnet-1.3.1-py3.6.egg/mxnet/gluon/block.py", line 912, in <dictcomp>
    params = {i: j.data(ctx) for i, j in self._reg_params.items()}
  File "/usr/local/lib/python3.6/dist-packages/mxnet-1.3.1-py3.6.egg/mxnet/gluon/parameter.py", line 494, in data
    return self._check_and_get(self._data, ctx)
  File "/usr/local/lib/python3.6/dist-packages/mxnet-1.3.1-py3.6.egg/mxnet/gluon/parameter.py", line 208, in _check_and_get
    "num_features, etc., for network layers."%(self.name))
mxnet.gluon.parameter.DeferredInitializationError: Parameter 'efficientnet0_conv1_weight' has not been initialized yet because initialization was deferred. Actual initialization happens during the first forward pass. Please pass one batch of data through the network before accessing Parameters. You can also avoid deferred initialization by specifying in_units, num_features, etc., for network layers.

The version of mxnet is 1.3.1,and the test code is as followsing:
 `  net.initialize()
    print(net.collect_params())

    data = mx.nd.random.randn(1, 3, 416, 416)
    y = net(data).asnumpy()
    print(y.shape)`

**Comment by AmigoCDT** [comment]
This is not a bug in MXNet. 
I think this is because that mxnet engine cannot infer the input shape of Conv2D. maybe we should pass `in_channels` parameter in `nn.Conv2D`. If so, I could fix this several days.
 **You could try add `in_channels` parameter in each Blocks using `nn.Conv2D`, and pass it to `nn.Conv2D`**

**Comment by AmigoCDT** [comment]
As [this](https://mxnet.incubator.apache.org/api/python/gluon/nn.html?highlight=conv2d#mxnet.gluon.nn.Conv2D) said:
>If in_channels is not specified, Parameter initialization will be deferred to the first time forward is called and in_channels will be inferred from the shape of input data.

This working rule is similar as the error message.

**Comment by AmigoCDT** [comment]
"b2" mode works well in my project. 
This error is because you didn't do a backward().  
In your test code: `y = net(data).asnumpy()` is just a forward. Without a backward, MXNet cannot do deferred initialization.

**Comment by nopattern** [comment]
Thank you . 
     I have tried to set in_channels in first Conv2D, and got the same error.  I think the problem will be solved if all in_channels be added . 
    Why is  the b2 version different with b0,b1?  

   I have change the test code to :
 
with autograd.record():
     net.initialize()
     print(net.collect_params())
     data = mx.nd.random.randn(1, 3, 416, 416)
     y = net(data).asnumpy()
     print(y.shape)

The result doesn't change .

**Comment by AmigoCDT** [comment]
The difference is width_coeff != 1.0 in "b2" mode, you can try "b3" mode, if "b3" also doesn't work, the problem is in width_coeff.

**Comment by nopattern** [comment]
b0,b1,b3,b6,b7 is good, b2,b4,b5 is bad. 
Are all good  on your pc?

**Comment by AmigoCDT** [comment]
Yeah, all are ok on my machine used in insightface.
I didn't use it to run other tasks, just face recognition.

**Comment by AmigoCDT** [comment]
In you err message: `Parameter 'efficientnet0_conv1_weight' has not been initialized yet because initialization was deferred.` 
When you set `in_channels` parameter in first conv2D, does the `efficientnet0_conv1_weight` in err messgae changed to `efficientnet0_conv2_weight`?

**Comment by AmigoCDT** [comment]
I've added `in_channels` in each conv2D and `in_units` in each Dense, you could have a try.

**Comment by nopattern** [comment]
all is good now.Thank you.But it  is strange why it needs in_channel,which should be defered in first data forward.
